name: Open release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

#
# TODO
# - Print versions name to commit, for easier Vercel deployments
#
jobs:
  release:
    name: Prepare release with Changesets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
        # Tags are fetched for Changeset to distinguish from new ones while running `changeset tag`
      - name: Git fetch tags
        run: git fetch --tags origin
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
        name: Install pnpm
      - run: pnpm install
      - name: Create Release Pull Request
        uses: changesets/action@e2f8e964d080ae97c874b19e27b12e0a8620fb6c # v1.4.6
        id: changesets
        with:
          title: 🚀 Release apps
          commit: Release apps
          publish: pnpm github:release
          createGithubReleases: true
        env:
          # Use private access token so Github can trigger another workflow from this one
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Find previous comment with checklist on release PR
        if: steps.changesets.outputs.hasChangesets == 'true'
        uses: peter-evans/find-comment@d5fe37641ad8451bdd80312415672ba26c86575e # v3.0.0
        id: find-comment
        with:
          issue-number: ${{ steps.changesets.outputs.pullRequestNumber }}
          body-includes: Releasing Avatax app checklist

      - name: Add release checklist comment to release PR
        if: steps.changesets.outputs.hasChangesets == 'true'
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ steps.changesets.outputs.pullRequestNumber }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            🚀 [Releasing Avatax app checklist](https://www.notion.so/saleor/Releasing-Avatax-app-checklist-5bf7928b942042e09e4197b70903c570?pvs=4)
